// frontend/src/app/(authenticated)/periods/page.tsx
"use client";

import { useState, useEffect } from "react";
import {
  IconCalendar,
  IconCalendarPlus,
  IconEye,
  IconEyeOff,
  IconPlus,
  IconLock,
  IconLockOpen,
  IconArrowLeft,
  IconAlertTriangle,
  IconX,
  IconInfoCircle,
  IconRefresh,
  IconCirclePlus,
  IconCalendarOff,
  IconLoader2,
} from "@tabler/icons-react";

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { cn } from "@/lib/utils";

import {
  useGetApiV1PeriodsQuery,
  useGetApiV1PeriodsOpenInfoQuery,
  usePostApiV1PeriodsMutation,
  usePostApiV1PeriodsSelectByIdMutation,
  usePostApiV1PeriodsClearSelectionMutation,
  usePostApiV1PeriodsCloseByIdMutation,
} from "@/lib/generatedApi";

interface ApiError { data?: { message?: string }; message?: string; }
interface AccountItem { id?: number | string; displayLabel?: string; referenceNumber?: string; accountName?: string; }
interface PeriodItem { id: number; periodName?: string; startDate?: string; endDate?: string; isClosed?: boolean; isSelected?: boolean; }

const MONTH_NAMES = ["January","February","March","April","May","June","July","August","September","October","November","December"];

export default function PeriodsPage() {
  const { data: rawPeriodsData, isLoading, refetch: refetchPeriods } = useGetApiV1PeriodsQuery();
  const { data: rawOpenInfoData, isLoading: isLoadingOpenInfo } = useGetApiV1PeriodsOpenInfoQuery();

  const [selectPeriodMutation] = usePostApiV1PeriodsSelectByIdMutation();
  const [clearSelectionMutation, { isLoading: isClearing }] = usePostApiV1PeriodsClearSelectionMutation();
  const [closePeriodMutation] = usePostApiV1PeriodsCloseByIdMutation();
  const [createPeriodMutation, { isLoading: isCreating }] = usePostApiV1PeriodsMutation();

  const periods: PeriodItem[] = Array.isArray(rawPeriodsData)? rawPeriodsData : (rawPeriodsData as any)?.items || (rawPeriodsData as any)?.periods || [];
  const selectedPeriod = periods.find((p) => p.isSelected) || null;
  const openInfo = (rawOpenInfoData as any) || null;

  const [viewMode, setViewMode] = useState<"list" | "create">("list");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [selectingId, setSelectingId] = useState<number | null>(null);
  const [closingId, setClosingId] = useState<number | null>(null);

  const [month, setMonth] = useState(1);
  const [year, setYear] = useState(2026);
  const [setupMode, setSetupMode] = useState<"LoadExisting" | "CreateNew">("LoadExisting");
  const [cashAccountId, setCashAccountId] = useState("");
  const [bankAccountId, setBankAccountId] = useState("");
  const [retainedId, setRetainedId] = useState("");
  const [cashAccountCode, setCashAccountCode] = useState("101");
  const [cashAccountName, setCashAccountName] = useState("Cash on Hand");
  const [cashBalance, setCashBalance] = useState<number | "">("");
  const [bankAccountCode, setBankAccountCode] = useState("102");
  const [bankAccountName, setBankAccountName] = useState("Bank Account");
  const [bankBalance, setBankBalance] = useState<number | "">("");
  const [retainedCode, setRetainedCode] = useState("301");
  const [retainedName, setRetainedName] = useState("Retained Earnings");

  useEffect(() => { const d = new Date(); setMonth(d.getMonth() + 1); setYear(d.getFullYear()); }, []);
  useEffect(() => {
    if (openInfo) {
      const exists =!!openInfo.hasExistingPermanentAccounts;
      setSetupMode(exists? "LoadExisting" : "CreateNew");
      if (exists) {
        setCashAccountId(openInfo.availableCashAndBankAccounts?.[0]?.id?.toString() || "");
        setBankAccountId(openInfo.availableCashAndBankAccounts?.[1]?.id?.toString() || openInfo.availableCashAndBankAccounts?.[0]?.id?.toString() || "");
        setRetainedId(openInfo.availableRetainedEarningsAccounts?.[0]?.id?.toString() || "");
      }
    }
  }, [openInfo]);

  const handleSelectPeriod = async (p: PeriodItem) => {
    setErrorMessage(null);
    setSelectingId(p.id);
    try {
      await selectPeriodMutation({ id: p.id }).unwrap();
      setSuccessMessage(`Now viewing: ${p.periodName}`);
      refetchPeriods();
    } catch (err) {
      const error = err as ApiError;
      setErrorMessage(error?.data?.message || "Gagal memilih periode.");
    } finally {
      setSelectingId(null);
    }
  };

  const handleClearSelection = async () => {
    setErrorMessage(null);
    try {
      await clearSelectionMutation().unwrap();
      setSuccessMessage("No period selected.");
      refetchPeriods();
    } catch (err) {
      const error = err as ApiError;
      setErrorMessage(error?.data?.message || "Gagal menghapus pilihan periode.");
    }
  };

  const handleClosePeriod = async (p: PeriodItem) => {
    if (!confirm(`Close ${p.periodName}? This will lock all entries.`)) return;
    setErrorMessage(null);
    setClosingId(p.id);
    try {
      await closePeriodMutation({ id: p.id }).unwrap();
      setSuccessMessage(`${p.periodName} closed successfully.`);
      refetchPeriods();
    } catch (err) {
      const error = err as ApiError;
      setErrorMessage(error?.data?.message || "Failed to close period.");
    } finally {
      setClosingId(null);
    }
  };

  const handleCreateSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMessage(null);
    if (setupMode === "LoadExisting" && (!cashAccountId ||!bankAccountId ||!retainedId)) {
      setErrorMessage("Select Cash, Bank, and Retained Earnings accounts."); return;
    }
    if (setupMode === "LoadExisting" && cashAccountId === bankAccountId) {
      setErrorMessage("Cash and Bank Account cannot be the same account."); return;
    }
    try {
      await createPeriodMutation({
        createPeriodRequest: {
          month, year, setupMode,
          cashAccountId: setupMode === "LoadExisting"? parseInt(cashAccountId, 10) : null,
          bankAccountId: setupMode === "LoadExisting"? parseInt(bankAccountId, 10) : null,
          retainedEarningsAccountId: setupMode === "LoadExisting"? parseInt(retainedId, 10) : null,
          cashAccountCode: setupMode === "CreateNew"? cashAccountCode : undefined,
          cashAccountName: setupMode === "CreateNew"? cashAccountName : undefined,
          cashBalance: setupMode === "CreateNew"? Number(cashBalance) || 0 : undefined,
          bankAccountCode: setupMode === "CreateNew"? bankAccountCode : undefined,
          bankAccountName: setupMode === "CreateNew"? bankAccountName : undefined,
          bankBalance: setupMode === "CreateNew"? Number(bankBalance) || 0 : undefined,
          retainedEarningsAccountCode: setupMode === "CreateNew"? retainedCode : undefined,
          retainedEarningsAccountName: setupMode === "CreateNew"? retainedName : undefined,
        },
      }).unwrap();
      setSuccessMessage("Period opened successfully.");
      setViewMode("list");
      refetchPeriods();
    } catch (err) {
      const error = err as ApiError;
      setErrorMessage(error?.data?.message || "Failed to create period.");
    }
  };

  return (
    <div className="space-y-6 max-w-5xl">
      {errorMessage && (
        <Alert variant="destructive" className="flex justify-between items-center py-2">
          <AlertDescription className="flex items-center gap-2 text-xs"><IconAlertTriangle size={16} />{errorMessage}</AlertDescription>
          <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => setErrorMessage(null)}><IconX size={14} /></Button>
        </Alert>
      )}
      {successMessage && (
        <Alert className="bg-emerald-500/10 border-emerald-500/20 text-emerald-600 dark:text-emerald-300 flex justify-between items-center py-2">
          <AlertDescription className="text-xs">{successMessage}</AlertDescription>
          <Button variant="ghost" size="icon" className="h-6 w-6 hover:bg-emerald-500/20" onClick={() => setSuccessMessage(null)}><IconX size={14} /></Button>
        </Alert>
      )}

      {viewMode === "list"? (
        <>
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h1 className="text-xl font-bold flex items-center gap-2"><IconCalendar className="text-primary" size={22} /> Accounting Periods</h1>
              <p className="text-sm text-muted-foreground mt-1">Period yang aktif akan dipakai di semua halaman dashboard</p>
            </div>
            <div className="flex gap-2">
              {selectedPeriod && (
                <Button variant="outline" size="sm" className="gap-1.5 border-primary/30 text-primary hover:bg-primary/10" onClick={handleClearSelection} disabled={isClearing}>
                  {isClearing? <IconLoader2 size={14} className="animate-spin" /> : <IconEyeOff size={14} />} Stop Viewing
                </Button>
              )}
              <Button size="sm" className="gap-1.5" onClick={() => setViewMode("create")}><IconPlus size={14} /> Open New Period</Button>
            </div>
          </div>

          <Card className="overflow-hidden">
            <CardHeader className="flex-row items-center justify-between space-y-0 py-3">
              <CardTitle className="text-sm">Period List</CardTitle>
              <Badge variant="secondary" className="font-mono text-xs">{periods.length} total</Badge>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="pl-6">Period Name</TableHead>
                    <TableHead>Start</TableHead>
                    <TableHead>End</TableHead>
                    <TableHead className="text-center">Status</TableHead>
                    <TableHead className="text-center pr-6 w-">Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {isLoading? (
                    <TableRow><TableCell colSpan={5} className="text-center py-8 text-muted-foreground"><IconLoader2 className="animate-spin inline mr-2" size={16} /> Loading...</TableCell></TableRow>
                  ) : (
                    periods.map((p) => {
                      const isSelected = selectedPeriod?.id === p.id;
                      const isSelectingThis = selectingId === p.id;
                      const isClosingThis = closingId === p.id;
                      return (
                        <TableRow key={p.id} className={cn("transition-colors", isSelected && "bg-primary/5 hover:bg-primary/10 border-l-4 border-l-primary", p.isClosed &&!isSelected && "opacity-60 bg-muted/30")}>
                          <TableCell className="pl-6 font-medium">
                            <div className="flex items-center gap-2">
                              <span className={cn("font-bold", isSelected && "text-primary")}>{p.periodName}</span>
                              {isSelected && <Badge className="gap-1 bg-primary text-white border-0 h-5 text-"><IconEye size={10} /> VIEWING</Badge>}
                            </div>
                          </TableCell>
                          <TableCell className="text-xs">{p.startDate? new Date(p.startDate).toLocaleDateString() : "-"}</TableCell>
                          <TableCell className="text-xs">{p.endDate? new Date(p.endDate).toLocaleDateString() : "-"}</TableCell>
                          <TableCell className="text-center">
                            {p.isClosed? <Badge variant="secondary" className="gap-1 h-6"><IconLock size={10} /> Closed</Badge> : <Badge className="gap-1 h-6 bg-emerald-500/15 text-emerald-600 border-emerald-500/20 hover:bg-emerald-500/15"><IconLockOpen size={10} /> Active</Badge>}
                          </TableCell>
                          <TableCell className="text-center pr-6">
                            <div className="flex justify-center gap-1.5">
                              <Button
                                type="button"
                                variant={isSelected? "default" : "outline"}
                                size="sm"
                                className={cn("h-7 min-w- gap-1.5 font-medium", isSelected? "bg-primary text-white shadow-sm hover:bg-primary/90" : "hover:bg-primary hover:text-white")}
                                onClick={() => handleSelectPeriod(p)}
                                disabled={isSelectingThis}
                              >
                                {isSelectingThis? <IconLoader2 size={14} className="animate-spin" /> : isSelected? <IconEyeOff size={14} /> : <IconEye size={14} />}
                                {isSelected? "Viewing" : "View"}
                              </Button>
                              {!p.isClosed && (
                                <Button type="button" variant="ghost" size="sm" className="h-7 w-7 px-0 hover:text-amber-600 hover:bg-amber-50 border hover:border-amber-200" onClick={() => handleClosePeriod(p)} disabled={isClosingThis}>
                                  {isClosingThis? <IconLoader2 size={14} className="animate-spin" /> : <IconLock size={14} />}
                                </Button>
                              )}
                            </div>
                          </TableCell>
                        </TableRow>
                      );
                    })
                  )}
                  {!isLoading && periods.length === 0 && (
                    <TableRow><TableCell colSpan={5} className="text-center py-12 text-muted-foreground"><IconCalendarOff className="mx-auto mb-2" size={28} /><p className="font-medium">No periods yet</p><p className="text-xs">Click Open New Period to start</p></TableCell></TableRow>
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </>
      ) : (
        <div className="max-w-4xl mx-auto space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-xl font-bold flex items-center gap-2"><IconCalendarPlus className="text-primary" size={22} /> Open New Period</h1>
              <p className="text-sm text-muted-foreground">Start monthly cycle. Opening balance posted on day 1.</p>
            </div>
            <Button variant="outline" size="sm" className="gap-1.5" onClick={() => setViewMode("list")}><IconArrowLeft size={14} /> Back</Button>
          </div>
          <form onSubmit={handleCreateSubmit} className="space-y-6">
            <Card>
              <CardHeader className="pb-3"><CardTitle className="text-sm">Period</CardTitle></CardHeader>
              <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-1.5"><Label>Month</Label><Select value={String(month)} onValueChange={(v) => setMonth(Number(v))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{MONTH_NAMES.map((n, i) => (<SelectItem key={i + 1} value={String(i + 1)}>{n}</SelectItem>))}</SelectContent></Select></div>
                <div className="space-y-1.5"><Label>Year</Label><Input type="number" value={year} onChange={(e) => setYear(Number(e.target.value))} required /></div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-3"><CardTitle className="text-sm">Permanent Accounts Setup</CardTitle><CardDescription>Choose existing or create new</CardDescription></CardHeader>
              <CardContent className="space-y-4">
                {isLoadingOpenInfo? (
                  <div className="text-center py-4 text-xs text-muted-foreground"><IconLoader2 className="animate-spin inline mr-1" size={14} /> Memuat informasi akun...</div>
                ) : (
                  <>
                    <RadioGroup value={setupMode} onValueChange={(v: "LoadExisting" | "CreateNew") => setSetupMode(v)} className="flex gap-4">
                      <div className="flex items-center gap-2"><RadioGroupItem value="LoadExisting" id="load" disabled={!openInfo?.hasExistingPermanentAccounts} /><Label htmlFor="load" className="flex items-center gap-1 text-xs cursor-pointer"><IconRefresh size={12} /> Use Existing</Label></div>
                      <div className="flex items-center gap-2"><RadioGroupItem value="CreateNew" id="create" /><Label htmlFor="create" className="flex items-center gap-1 text-xs cursor-pointer"><IconCirclePlus size={12} /> Register New</Label></div>
                    </RadioGroup>
                    {!openInfo?.hasExistingPermanentAccounts && (
                      <Alert className="bg-blue-500/10 border-blue-500/20 text-blue-600 dark:text-blue-300"><IconInfoCircle size={16} /><AlertDescription className="text-xs">No existing Cash/Bank & Retained accounts found - new accounts required</AlertDescription></Alert>
                    )}
                    {setupMode === "LoadExisting"? (
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div className="space-y-1.5"><Label>Cash Account</Label><Select value={cashAccountId} onValueChange={setCashAccountId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{openInfo?.availableCashAndBankAccounts?.map((a: AccountItem) => (<SelectItem key={a.id} value={a.id?.toString() || ""}>{a.displayLabel || `${a.referenceNumber} - ${a.accountName}`}</SelectItem>))}</SelectContent></Select></div>
                        <div className="space-y-1.5"><Label>Bank Account</Label><Select value={bankAccountId} onValueChange={setBankAccountId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{openInfo?.availableCashAndBankAccounts?.map((a: AccountItem) => (<SelectItem key={a.id} value={a.id?.toString() || ""}>{a.displayLabel || `${a.referenceNumber} - ${a.accountName}`}</SelectItem>))}</SelectContent></Select></div>
                        <div className="space-y-1.5"><Label>Retained Earnings</Label><Select value={retainedId} onValueChange={setRetainedId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{openInfo?.availableRetainedEarningsAccounts?.map((a: AccountItem) => (<SelectItem key={a.id} value={a.id?.toString() || ""}>{a.displayLabel || `${a.referenceNumber} - ${a.accountName}`}</SelectItem>))}</SelectContent></Select></div>
                      </div>
                    ) : (
                      <div className="space-y-4">
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                          <div className="space-y-1.5"><Label>Cash Code</Label><Input value={cashAccountCode} onChange={(e) => setCashAccountCode(e.target.value)} /></div>
                          <div className="space-y-1.5"><Label>Cash Name</Label><Input value={cashAccountName} onChange={(e) => setCashAccountName(e.target.value)} /></div>
                          <div className="space-y-1.5"><Label>Cash Balance</Label><Input type="number" value={cashBalance} onChange={(e) => setCashBalance(e.target.value === ""? "" : Number(e.target.value))} /></div>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                          <div className="space-y-1.5"><Label>Bank Code</Label><Input value={bankAccountCode} onChange={(e) => setBankAccountCode(e.target.value)} /></div>
                          <div className="space-y-1.5"><Label>Bank Name</Label><Input value={bankAccountName} onChange={(e) => setBankAccountName(e.target.value)} /></div>
                          <div className="space-y-1.5"><Label>Bank Balance</Label><Input type="number" value={bankBalance} onChange={(e) => setBankBalance(e.target.value === ""? "" : Number(e.target.value))} /></div>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div className="space-y-1.5"><Label>Retained Code</Label><Input value={retainedCode} onChange={(e) => setRetainedCode(e.target.value)} /></div>
                          <div className="space-y-1.5"><Label>Retained Name</Label><Input value={retainedName} onChange={(e) => setRetainedName(e.target.value)} /></div>
                        </div>
                      </div>
                    )}
                  </>
                )}
              </CardContent>
            </Card>
            <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setViewMode("list")}>Cancel</Button><Button type="submit" disabled={isCreating}>{isCreating? "Creating..." : "Submit Period"}</Button></div>
          </form>
        </div>
      )}
    </div>
  );
}

// nuxtjs/app/pages/periods.vue
<script setup lang="ts">
definePageMeta({
  layout: 'default'
})

interface PeriodRaw {
  Id: number
  PeriodName: string
  StartDate: string
  EndDate: string
  IsClosed: boolean
  IsSelected: boolean
}

interface PeriodItem {
  id: number
  periodName: string
  startDate: string
  endDate: string
  isClosed: boolean
  isSelected: boolean
}

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
]

const ENDPOINTS = {
  LIST: '/api/v1/periods',
  CREATE: '/api/v1/periods',
  SELECT: (id: number) => `/api/v1/periods/${id}/select`,
  CLEAR: '/api/v1/periods/clear-selection',
  CLOSE: (id: number) => `/api/v1/periods/${id}/close`,
}

const viewMode = ref<'list' | 'create'>('list')
const errorMessage = ref<string | null>(null)
const successMessage = ref<string | null>(null)
const selectingId = ref<number | null>(null)
const closingId = ref<number | null>(null)
const isClearing = ref(false)
const isCreating = ref(false)
const isLoading = ref(false)

const periods = ref<PeriodItem[]>([])
const month = ref(new Date().getMonth() + 1)
const year = ref(new Date().getFullYear())

const monthOptions = MONTH_NAMES.map((label, i) => ({ label, value: i + 1 }))
const selectedPeriod = computed(() => periods.value.find(p => p.isSelected) || null)

const mapRaw = (raw: PeriodRaw[]): PeriodItem[] => {
  return raw.map(r => ({
    id: r.Id,
    periodName: r.PeriodName,
    startDate: r.StartDate,
    endDate: r.EndDate,
    isClosed: r.IsClosed,
    isSelected: r.IsSelected
  }))
}

const fetchPeriods = async () => {
  isLoading.value = true
  try {
    const raw: any = await $fetch(ENDPOINTS.LIST)
    const arr = Array.isArray(raw) ? raw : raw?.items || []
    periods.value = mapRaw(arr as PeriodRaw[])
  } catch (e: any) {
    errorMessage.value = e?.data?.message || e?.message || 'Gagal load periods'
  } finally {
    isLoading.value = false
  }
}

const handleSelectPeriod = async (p: PeriodItem) => {
  errorMessage.value = null
  selectingId.value = p.id
  try {
    await $fetch(ENDPOINTS.SELECT(p.id), { method: 'POST' })
    successMessage.value = `Now viewing: ${p.periodName}`
    await fetchPeriods()
  } catch (err: any) {
    errorMessage.value = err?.data?.message || 'Gagal memilih periode.'
  } finally {
    selectingId.value = null
  }
}

const handleClearSelection = async () => {
  errorMessage.value = null
  isClearing.value = true
  try {
    await $fetch(ENDPOINTS.CLEAR, { method: 'POST' })
    successMessage.value = 'No period selected.'
    await fetchPeriods()
  } catch (err: any) {
    errorMessage.value = err?.data?.message || 'Gagal clear selection.'
  } finally {
    isClearing.value = false
  }
}

const handleClosePeriod = async (p: PeriodItem) => {
  if (!confirm(`Close ${p.periodName}? Ini akan lock semua transaksi di periode ini.`)) return
  errorMessage.value = null
  closingId.value = p.id
  try {
    await $fetch(ENDPOINTS.CLOSE(p.id), { method: 'POST' })
    successMessage.value = `${p.periodName} closed.`
    await fetchPeriods()
  } catch (err: any) {
    errorMessage.value = err?.data?.message || 'Failed to close period.'
  } finally {
    closingId.value = null
  }
}

const handleCreateSubmit = async () => {
  errorMessage.value = null
  isCreating.value = true
  try {
    await $fetch(ENDPOINTS.CREATE, {
      method: 'POST',
      body: { month: month.value, year: year.value }
    })
    successMessage.value = 'Period opened successfully.'
    viewMode.value = 'list'
    await fetchPeriods()
  } catch (err: any) {
    errorMessage.value = err?.data?.message || err?.message || 'Gagal create period.'
  } finally {
    isCreating.value = false
  }
}

const formatDate = (d?: string) => d ? new Date(d).toLocaleDateString('id-ID') : '-'

onMounted(fetchPeriods)
</script>

<template>
  <div class="space-y-6 max-w-5xl mx-auto p-4">
    <UAlert v-if="errorMessage" color="error" variant="subtle" :title="errorMessage" icon="i-lucide-triangle-alert" :close-button="{ icon: 'i-lucide-x' }" @close="errorMessage = null" />
    <UAlert v-if="successMessage" color="success" variant="subtle" :title="successMessage" icon="i-lucide-check-circle" :close-button="{ icon: 'i-lucide-x' }" @close="successMessage = null" />

    <div v-if="viewMode === 'list'">
      <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <div>
          <h1 class="text-xl font-bold flex items-center gap-2"><UIcon name="i-lucide-calendar" class="size-5" /> Accounting Periods</h1>
          <p class="text-sm text-muted mt-1">Period yang aktif akan dipakai di semua halaman</p>
        </div>
        <div class="flex gap-2">
          <UButton v-if="selectedPeriod" variant="outline" size="sm" :loading="isClearing" icon="i-lucide-eye-off" @click="handleClearSelection">Stop Viewing</UButton>
          <UButton size="sm" icon="i-lucide-plus" @click="viewMode = 'create'">Open New Period</UButton>
        </div>
      </div>

      <UCard class="overflow-hidden bg-[#151519] border border-white/[0.07]" :ui="{ body: 'p-0' }">
        <template #header>
          <div class="flex items-center justify-between py-1">
            <span class="text-sm font-semibold text-white">Period List</span>
            <UBadge variant="subtle" color="neutral">{{ periods.length }} total</UBadge>
          </div>
        </template>
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead>
              <tr class="border-b border-white/[0.06] text-zinc-500 text-left">
                <th class="pl-6 py-3">Period Name</th>
                <th>Start</th>
                <th>End</th>
                <th class="text-center">Status</th>
                <th class="pr-6 text-center">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="isLoading"><td colspan="5" class="text-center py-8 text-zinc-500"><UIcon name="i-lucide-loader-2" class="animate-spin inline mr-2" /> Loading...</td></tr>
              <tr v-for="p in periods" :key="p.id" class="border-b border-white/[0.06]" :class="[selectedPeriod?.id === p.id ? 'bg-white/[0.06] border-l-4 border-l-white' : 'hover:bg-white/[0.03]', p.isClosed && selectedPeriod?.id !== p.id ? 'opacity-50' : '']">
                <td class="pl-6 py-3 flex items-center gap-2">
                  <span :class="selectedPeriod?.id === p.id ? 'text-white font-bold' : 'text-zinc-200'">{{ p.periodName }}</span>
                  <UBadge v-if="selectedPeriod?.id === p.id" class="bg-white text-black font-bold">VIEWING</UBadge>
                </td>
                <td class="text-xs text-zinc-400">{{ formatDate(p.startDate) }}</td>
                <td class="text-xs text-zinc-400">{{ formatDate(p.endDate) }}</td>
                <td class="text-center">
                  <UBadge v-if="p.isClosed" color="neutral" variant="subtle"><UIcon name="i-lucide-lock" class="size-3" /> Closed</UBadge>
                  <UBadge v-else color="success" variant="subtle"><UIcon name="i-lucide-lock-open" class="size-3" /> Active</UBadge>
                </td>
                <td class="pr-6 py-3">
                  <div class="flex justify-center gap-1.5">
                    <UButton size="xs" :loading="selectingId === p.id" :icon="selectedPeriod?.id === p.id ? 'i-lucide-eye-off' : 'i-lucide-eye'" :variant="selectedPeriod?.id === p.id ? 'solid' : 'outline'" @click="handleSelectPeriod(p)">{{ selectedPeriod?.id === p.id ? 'VIEWING' : 'VIEW' }}</UButton>
                    <UButton v-if="!p.isClosed" size="xs" variant="ghost" icon="i-lucide-lock" :loading="closingId === p.id" @click="handleClosePeriod(p)" />
                  </div>
                </td>
              </tr>
              <tr v-if="!isLoading && periods.length === 0"><td colspan="5" class="text-center py-12 text-zinc-500"><UIcon name="i-lucide-calendar-off" class="size-7 mx-auto mb-2 block" />No periods yet</td></tr>
            </tbody>
          </table>
        </div>
      </UCard>
    </div>

    <div v-else class="max-w-xl mx-auto space-y-6">
      <div class="flex items-center justify-between">
        <h1 class="text-xl font-bold flex items-center gap-2"><UIcon name="i-lucide-calendar-plus" class="size-5" /> Open New Period</h1>
        <UButton variant="outline" size="sm" icon="i-lucide-arrow-left" @click="viewMode = 'list'">Back</UButton>
      </div>
      <form @submit.prevent="handleCreateSubmit" class="space-y-6">
        <UCard class="bg-[#151519] border border-white/[0.07]">
          <div class="grid grid-cols-2 gap-4">
            <UFormField label="Month"><USelect v-model="month" :items="monthOptions" class="w-full" /></UFormField>
            <UFormField label="Year"><UInput v-model.number="year" type="number" required /></UFormField>
          </div>
        </UCard>
        <div class="flex justify-end gap-2">
          <UButton variant="outline" @click="viewMode = 'list'">Cancel</UButton>
          <UButton type="submit" :loading="isCreating">Submit Period</UButton>
        </div>
      </form>
    </div>
  </div>
</template>
