// nuxtjs/app/pages/reports/index.vue
<!-- pages/reports/index.vue -->
<script setup lang="ts">
definePageMeta({
  layout: 'default'
})

// Quick stats / Summary ringkasan keuangan
const summaryStats = ref([
  {
    title: 'Total Transaksi Jurnal',
    value: '1,284',
    change: '+12%',
    icon: 'i-lucide-notebook-tabs',
    color: 'text-blue-500'
  },
  {
    title: 'Total Akun Aktif',
    value: '48',
    change: 'COA Aktif',
    icon: 'i-lucide-book-open',
    color: 'text-emerald-500'
  },
  {
    title: 'Periode Berjalan',
    value: 'Q3 2026',
    change: 'Status: Terbuka',
    icon: 'i-lucide-calendar-range',
    color: 'text-amber-500'
  }
])

// Daftar Kategori & Menu Laporan Keuangan
const reportCategories = ref([
  {
    category: 'Laporan Akuntansi Utama',
    description: 'Pencatatan harian, buku besar, dan pencocokan saldo akun.',
    items: [
      {
        title: 'General Journal Report',
        description: 'Daftar rinci seluruh jurnal umum pencatatan debit & kredit harian.',
        to: '/reports/general-journal',
        icon: 'i-lucide-notebook-tabs',
        badge: 'Utama'
      },
      {
        title: 'General Ledger (Buku Besar)',
        description: 'Rincian pergerakan saldo dan mutasi untuk setiap akun COA.',
        to: '/reports/general-ledger',
        icon: 'i-lucide-book-marked',
        badge: 'Segera'
      },
      {
        title: 'Trial Balance (Neraca Saldo)',
        description: 'Ringkasan total debit dan kredit dari seluruh akun COA.',
        to: '/reports/trial-balance',
        icon: 'i-lucide-scale',
        badge: 'Segera'
      }
    ]
  },
  {
    category: 'Laporan Keuangan Eksekutif',
    description: 'Analisis laba rugi, posisi keuangan, dan arus kas usaha.',
    items: [
      {
        title: 'Income Statement (Laba Rugi)',
        description: 'Ringkasan pendapatan, beban, dan profit bersih perusahaan.',
        to: '/reports/income-statement',
        icon: 'i-lucide-trending-up',
        badge: 'Rencana'
      },
      {
        title: 'Balance Sheet (Neraca Keuangan)',
        description: 'Gambaran Aset, Liabilitas (Hutang), dan Ekuitas (Modal).',
        to: '/reports/balance-sheet',
        icon: 'i-lucide-landmark',
        badge: 'Rencana'
      }
    ]
  }
])
</script>

<template>
  <UDashboardPage>
    <UDashboardPanel grow>
      <!-- Header Landing Page -->
      <UDashboardNavbar title="Financial Reports" badge="Pusat Laporan">
        <template #right>
          <UButton
            icon="i-lucide-calendar"
            color="neutral"
            variant="outline"
            label="Filter Periode"
          />
        </template>
      </UDashboardNavbar>

      <UDashboardPanelContent class="space-y-8 p-6">
        <!-- Banner Intro -->
        <div class="rounded-xl bg-gradient-to-r from-blue-600/10 via-indigo-500/10 to-purple-500/10 p-6 border border-blue-500/20">
          <div class="flex items-start justify-between">
            <div class="space-y-2">
              <h2 class="text-xl font-bold tracking-tight">Pusat Laporan & Analytics Keuangan</h2>
              <p class="text-sm text-neutral-500 dark:text-neutral-400 max-w-2xl">
                Akses seluruh laporan akuntansi, audit pencatatan jurnal umum, hingga analisis neraca keuangan secara terpusat dan konsisten.
              </p>
            </div>
            <UIcon name="i-lucide-file-pie-chart" class="w-12 h-12 text-blue-500 hidden sm:block opacity-80" />
          </div>
        </div>

        <!-- Quick Summary Cards -->
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <UCard v-for="(stat, idx) in summaryStats" :key="idx" class="relative overflow-hidden">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-xs font-medium text-neutral-500 dark:text-neutral-400">{{ stat.title }}</p>
                <p class="text-2xl font-bold mt-1">{{ stat.value }}</p>
                <span class="text-xs text-emerald-600 font-medium mt-1 inline-block">{{ stat.change }}</span>
              </div>
              <div class="p-3 bg-neutral-100 dark:bg-neutral-800 rounded-lg">
                <UIcon :name="stat.icon" class="w-6 h-6" :class="stat.color" />
              </div>
            </div>
          </UCard>
        </div>

        <!-- Section List Kategori Laporan -->
        <div v-for="(group, gIdx) in reportCategories" :key="gIdx" class="space-y-4">
          <div>
            <h3 class="text-lg font-semibold text-neutral-800 dark:text-neutral-100">{{ group.category }}</h3>
            <p class="text-xs text-neutral-500 dark:text-neutral-400">{{ group.description }}</p>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <NuxtLink
              v-for="(item, iIdx) in group.items"
              :key="iIdx"
              :to="item.to"
              class="group block"
            >
              <UCard
                class="h-full transition-all duration-200 hover:border-blue-500 hover:shadow-md cursor-pointer relative"
              >
                <div class="space-y-3">
                  <div class="flex items-center justify-between">
                    <div class="p-2.5 bg-blue-50 dark:bg-blue-950/50 rounded-lg text-blue-600 dark:text-blue-400 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                      <UIcon :name="item.icon" class="w-5 h-5" />
                    </div>
                    <UBadge
                      :color="item.badge === 'Utama' ? 'primary' : 'neutral'"
                      variant="subtle"
                      size="xs"
                    >
                      {{ item.badge }}
                    </UBadge>
                  </div>

                  <div>
                    <h4 class="font-semibold text-sm group-hover:text-blue-600 dark:group-hover:text-blue-400 flex items-center gap-1">
                      {{ item.title }}
                      <UIcon name="i-lucide-arrow-right" class="w-4 h-4 opacity-0 group-hover:opacity-100 -translate-x-2 group-hover:translate-x-0 transition-all" />
                    </h4>
                    <p class="text-xs text-neutral-500 dark:text-neutral-400 mt-1 line-clamp-2">
                      {{ item.description }}
                    </p>
                  </div>
                </div>
              </UCard>
            </NuxtLink>
          </div>
        </div>
      </UDashboardPanelContent>
    </UDashboardPanel>
  </UDashboardPage>
</template>

// frontend/src/app/(authenticated)/reports/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import {
  IconReportAnalytics,
  IconClipboardList,
  IconTable,
  IconNotebook,
  IconFileInvoice,
  IconBook,
  IconBooks,
  IconChartBar,
  IconCoins,
  IconBuildingBank,
  IconCashBanknote,
  IconFileSpreadsheet,
  IconSearch,
  IconArrowRight,
  IconFileCheck,
} from "@tabler/icons-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";

type ReportItem = {
  slug: string;
  title: string;
  desc: string;
  category: string;
  step: string;
  icon: any;
};

const REPORTS: ReportItem[] = [
  // Trial Balance Cycle
  {
    slug: "unadjusted-trial-balance",
    title: "Unadjusted Trial Balance",
    desc: "Neraca saldo awal sebelum penyesuaian",
    category: "Trial Balance Cycle",
    step: "01",
    icon: IconClipboardList,
  },
  {
    slug: "worksheet",
    title: "Worksheet",
    desc: "10-column worksheet & kertas kerja",
    category: "Trial Balance Cycle",
    step: "02",
    icon: IconTable,
  },
  {
    slug: "adjusting-journal",
    title: "Adjusting Journal",
    desc: "Jurnal penyesuaian akhir periode",
    category: "Trial Balance Cycle",
    step: "03",
    icon: IconNotebook,
  },
  {
    slug: "adjusted-trial-balance",
    title: "Adjusted Trial Balance",
    desc: "Neraca saldo setelah penyesuaian",
    category: "Trial Balance Cycle",
    step: "04",
    icon: IconFileCheck,
  },
  // Journals & Ledgers
  {
    slug: "general-journal",
    title: "General Journal",
    desc: "Buku harian semua transaksi",
    category: "Journals & Ledgers",
    step: "05",
    icon: IconFileInvoice,
  },
  {
    slug: "general-ledger-temporary",
    title: "General Ledger - Temporary",
    desc: "Buku besar akun nominal",
    category: "Journals & Ledgers",
    step: "06",
    icon: IconBook,
  },
  {
    slug: "general-ledger-permanent",
    title: "General Ledger - Permanent",
    desc: "Buku besar akun riil",
    category: "Journals & Ledgers",
    step: "07",
    icon: IconBooks,
  },
  // Financial Statements
  {
    slug: "income-statement",
    title: "Income Statement",
    desc: "Laporan laba rugi periode berjalan",
    category: "Financial Statements",
    step: "08",
    icon: IconChartBar,
  },
  {
    slug: "retained-earnings",
    title: "Retained Earnings",
    desc: "Laporan perubahan modal & laba ditahan",
    category: "Financial Statements",
    step: "09",
    icon: IconCoins,
  },
  {
    slug: "statement-of-financial-position",
    title: "Financial Position",
    desc: "Neraca / Statement of Financial Position",
    category: "Financial Statements",
    step: "10",
    icon: IconBuildingBank,
  },
  {
    slug: "statement-of-cash-flow",
    title: "Cash Flow Statement",
    desc: "Arus kas operasi, investasi, pendanaan",
    category: "Financial Statements",
    step: "11",
    icon: IconCashBanknote,
  },
  // Closing Cycle
  {
    slug: "closing-journal",
    title: "Closing Journal",
    desc: "Jurnal penutup akun nominal",
    category: "Closing Cycle",
    step: "12",
    icon: IconNotebook,
  },
  {
    slug: "post-closing-trial-balance",
    title: "Post-Closing Trial Balance",
    desc: "Neraca saldo setelah penutupan",
    category: "Closing Cycle",
    step: "13",
    icon: IconFileSpreadsheet,
  },
];

const CATEGORIES = [
  {
    id: "Trial Balance Cycle",
    label: "Trial Balance & Worksheet",
    hint: "Tahap awal hingga penyesuaian",
  },
  {
    id: "Journals & Ledgers",
    label: "Journals & Ledgers",
    hint: "Pencatatan harian & buku besar",
  },
  {
    id: "Financial Statements",
    label: "Financial Statements",
    hint: "Output utama laporan keuangan",
  },
  {
    id: "Closing Cycle",
    label: "Closing Cycle",
    hint: "Penutupan & saldo awal periode baru",
  },
];

export default function ReportsPage() {
  const [q, setQ] = useState("");

  const filtered = REPORTS.filter((r) =>
    `${r.title} ${r.desc} ${r.slug}`.toLowerCase().includes(q.toLowerCase())
  );

  return (
    <div className="grid w-full place-items-center py-6">
      <Card className="w-full max-w-5xl rounded-2xl border border-white/10 bg-[#0F172A] p-6 text-white shadow-2xl">
        <CardContent className="p-6 md:p-8">
          {/* Breadcrumb */}
          <Breadcrumb className="mb-6">
            <BreadcrumbList className="text-white/50">
              <BreadcrumbItem>
                <BreadcrumbLink asChild>
                  <Link href="/" className="hover:text-white">Home</Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator className="text-white/20" />
              <BreadcrumbItem>
                <BreadcrumbPage className="text-white">Reports</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>

          {/* Header */}
          <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
            <div className="flex gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-indigo-300/20 bg-gradient-to-br from-indigo-500/80 to-violet-600/80 shadow-lg">
                <IconReportAnalytics size={24} />
              </div>
              <div>
                <h1 className="text-xl font-bold tracking-tight md:text-2xl">
                  Reports Center
                </h1>
                <p className="mt-1 max-w-xl text-sm leading-relaxed text-white/60">
                  Akses 13 laporan siklus akuntansi lengkap. Dari unadjusted trial balance sampai post-closing. Pilih laporan untuk melihat detail & export.
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-emerald-500/20 bg-emerald-500/10 text-emerald-400"
              >
                {REPORTS.length} REPORTS
              </Badge>
              <Badge
                variant="outline"
                className="border-white/10 bg-white/5 text-white/60"
              >
                ACCOUNTING CYCLE
              </Badge>
            </div>
          </div>

          {/* Search */}
          <div className="relative mt-6">
            <IconSearch
              size={16}
              className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-white/40"
            />
            <Input
              value={q}
              onChange={(e) => setQ(e.target.value)}
              placeholder="Cari laporan: journal, ledger, cash flow..."
              className="h-11 rounded-xl border-white/10 bg-black/40 pl-10 text-white placeholder:text-white/30 focus-visible:ring-indigo-500/50"
            />
          </div>

          <Separator className="my-6 bg-white/10" />

          {/* Categories */}
          <div className="space-y-8">
            {CATEGORIES.map((cat) => {
              const items = filtered.filter((r) => r.category === cat.id);
              if (items.length === 0) return null;

              return (
                <div key={cat.id}>
                  <div className="mb-3 flex items-baseline justify-between">
                    <h2 className="text-sm font-semibold tracking-wide text-white/90">
                      {cat.label}
                    </h2>
                    <span className="text- text-white/40">
                      {cat.hint}
                    </span>
                  </div>

                  <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
                    {items.map((report) => {
                      const Icon = report.icon;
                      return (
                        <Link
                          key={report.slug}
                          href={`/reports/${report.slug}`}
                          className="group relative flex items-start gap-3 rounded-xl border border-white/10 bg-black/40 p-4 transition-all hover:border-indigo-500/30 hover:bg-white/[0.06]"
                        >
                          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-slate-900/80 text-white/80 group-hover:border-indigo-400/30 group-hover:text-white">
                            <Icon size={18} />
                          </div>

                          <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-2">
                              <span className="truncate text-sm font-semibold text-white group-hover:text-white">
                                {report.title}
                              </span>
                              <span className="rounded bg-white/10 px-1.5 py-0.5 text- font-mono text-white/40">
                                {report.step}
                              </span>
                            </div>
                            <p className="mt-0.5 line-clamp-1 text-xs text-white/50">
                              {report.desc}
                            </p>
                            <div className="mt-2 flex items-center gap-1 text- text-white/30 group-hover:text-indigo-300">
                              <span>/reports/{report.slug}</span>
                              <IconArrowRight
                                size={12}
                                className="opacity-0 transition-all group-hover:translate-x-0.5 group-hover:opacity-100"
                              />
                            </div>
                          </div>
                        </Link>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>

          {filtered.length === 0 && (
            <div className="mt-10 rounded-xl border border-white/10 bg-black/40 py-10 text-center">
              <p className="text-sm text-white/50">
                Tidak ada laporan untuk &quot;{q}&quot;
              </p>
            </div>
          )}

          {/* Flow Footer */}
          <div className="mt-8 rounded-xl border border-white/10 bg-slate-900/80 p-4">
            <div className="flex flex-wrap items-center gap-2 text- text-white/40">
              <span className="text-white/60">Flow:</span>
              <Badge className="border-0 bg-white/10 text- text-white/60">UTB</Badge>
              <span>→</span>
              <Badge className="border-0 bg-white/10 text- text-white/60">Worksheet</Badge>
              <span>→</span>
              <Badge className="border-0 bg-amber-500/15 text- text-amber-300">ATB</Badge>
              <span>→</span>
              <Badge className="border-0 bg-indigo-500/20 text- text-indigo-300">Financial Statements</Badge>
              <span>→</span>
              <Badge className="border-0 bg-emerald-500/15 text- text-emerald-300">PCTB</Badge>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
